begin;

-- ============================================================
-- TAIHENBET 2.0 — FASE 3.17
-- CENTRAL DE NOTIFICACOES
-- Execute depois da 3.16a.
-- ============================================================

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  message text not null,
  target_page text,
  target_entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists user_notifications_user_created_idx
  on public.user_notifications (user_id, created_at desc);
create index if not exists user_notifications_user_unread_idx
  on public.user_notifications (user_id, created_at desc)
  where read_at is null;

-- Habilita entrega em tempo real quando o projeto usa a publicação padrão do Supabase.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
       from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'user_notifications'
     ) then
    execute 'alter publication supabase_realtime add table public.user_notifications';
  end if;
end $$;

alter table public.user_notifications enable row level security;
revoke all on table public.user_notifications from anon, authenticated;
grant select on table public.user_notifications to authenticated;

drop policy if exists "users read own notifications" on public.user_notifications;
create policy "users read own notifications"
on public.user_notifications
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public._notify_user(
  p_user_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_target_page text default null,
  p_target_entity_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  if p_user_id is null then return null; end if;

  insert into public.user_notifications (
    user_id, type, title, message, target_page, target_entity_id, metadata
  ) values (
    p_user_id,
    left(coalesce(nullif(trim(p_type), ''), 'system'), 40),
    left(coalesce(nullif(trim(p_title), ''), 'Comunicado da banca'), 120),
    left(coalesce(nullif(trim(p_message), ''), 'A Entidade registrou um novo evento.'), 700),
    nullif(left(trim(coalesce(p_target_page, '')), 50), ''),
    nullif(left(trim(coalesce(p_target_entity_id, '')), 160), ''),
    case when jsonb_typeof(coalesce(p_metadata, '{}'::jsonb)) = 'object'
      then coalesce(p_metadata, '{}'::jsonb) else '{}'::jsonb end
  ) returning id into v_id;

  return v_id;
end;
$$;
revoke all on function public._notify_user(uuid,text,text,text,text,text,jsonb) from public;

create or replace function public.push_my_notification(
  p_type text,
  p_title text,
  p_message text,
  p_target_page text default null,
  p_target_entity_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_type text := lower(trim(coalesce(p_type, 'system')));
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if v_type not in ('game_result','bonus','system') then
    raise exception 'Client notification type not allowed';
  end if;

  return public._notify_user(
    v_uid, v_type, p_title, p_message,
    p_target_page, p_target_entity_id, p_metadata
  );
end;
$$;
revoke all on function public.push_my_notification(text,text,text,text,text,jsonb) from public;
grant execute on function public.push_my_notification(text,text,text,text,text,jsonb) to authenticated;

create or replace function public.get_my_notifications(p_limit integer default 60)
returns table (
  id bigint,
  type text,
  title text,
  message text,
  target_page text,
  target_entity_id text,
  metadata jsonb,
  read_at timestamptz,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select n.id, n.type, n.title, n.message, n.target_page,
         n.target_entity_id, n.metadata, n.read_at, n.created_at
  from public.user_notifications n
  where n.user_id = auth.uid()
  order by n.created_at desc
  limit least(100, greatest(1, coalesce(p_limit, 60)));
$$;
revoke all on function public.get_my_notifications(integer) from public;
grant execute on function public.get_my_notifications(integer) to authenticated;

create or replace function public.mark_my_notification_read(p_notification_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.user_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id and user_id = auth.uid();
  return found;
end;
$$;
revoke all on function public.mark_my_notification_read(bigint) from public;
grant execute on function public.mark_my_notification_read(bigint) to authenticated;

create or replace function public.mark_all_my_notifications_read()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  update public.user_notifications
  set read_at = now()
  where user_id = auth.uid() and read_at is null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.mark_all_my_notifications_read() from public;
grant execute on function public.mark_all_my_notifications_read() to authenticated;

create or replace function public.clear_my_read_notifications()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  delete from public.user_notifications
  where user_id = auth.uid() and read_at is not null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.clear_my_read_notifications() from public;
grant execute on function public.clear_my_read_notifications() to authenticated;

-- ---------- Conquistas ----------
create or replace function public._notification_achievement_name(p_key text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_key
    when 'primeiro_bilhete' then 'Primeiro sacrifício'
    when 'analista_bahrein' then 'Analista do Bahrein'
    when 'primeira_vitoria' then 'Milagre estatístico'
    when 'cliente_banca' then 'Cliente preferencial'
    when 'domador_taigrinho' then 'Domador de Taigrinho'
    when 'agronomo_risco' then 'Agricultura de risco'
    when 'fugitivo_regime' then 'Fuga do regime'
    when 'joquei_mambo' then 'Protocolo Mambo'
    when 'investidor_questionavel' then 'Investidor questionável'
    when 'inimigo_banca' then 'Inimigo da banca'
    when 'veterano_ruina' then 'Veterano da ruína'
    else p_key
  end;
$$;
revoke all on function public._notification_achievement_name(text) from public;

create or replace function public._notification_title_name(p_key text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_key
    when 'primeiro_bilhete' then 'Apostador de Schrödinger'
    when 'analista_bahrein' then 'Especialista em Futebol Bareinita'
    when 'primeira_vitoria' then 'Milagre Estatístico'
    when 'cliente_banca' then 'Cliente Preferencial da Banca'
    when 'domador_taigrinho' then 'Domador de Taigrinho'
    when 'agronomo_risco' then 'Agrônomo de Risco'
    when 'fugitivo_regime' then 'Fugitivo do Regime'
    when 'joquei_mambo' then 'Jóquei do Protocolo Mambo'
    when 'investidor_questionavel' then 'Investidor Questionável'
    when 'inimigo_banca' then 'Inimigo da Banca'
    when 'veterano_ruina' then 'Veterano da Ruína'
    else p_key
  end;
$$;
revoke all on function public._notification_title_name(text) from public;

create or replace function public._notify_achievement_unlocked()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public._notify_user(
    new.user_id,
    'achievement',
    'Conquista desbloqueada',
    'Você desbloqueou "' || public._notification_achievement_name(new.achievement_key) || '". A banca registrou o feito.',
    'progresso',
    new.achievement_key,
    jsonb_build_object('achievement_key', new.achievement_key)
  );
  return new;
end;
$$;

drop trigger if exists taihenbet_notify_achievement on public.user_achievements;
create trigger taihenbet_notify_achievement
after insert on public.user_achievements
for each row execute function public._notify_achievement_unlocked();

-- ---------- Titulos ----------
create or replace function public._notify_title_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.equipped_title_key is distinct from new.equipped_title_key then
    perform public._notify_user(
      new.id,
      'title',
      case when new.equipped_title_key is null then 'Título removido' else 'Título equipado' end,
      case when new.equipped_title_key is null
        then 'Seu perfil voltou a circular sem título oficial.'
        else 'Seu perfil agora exibe "' || public._notification_title_name(new.equipped_title_key) || '".'
      end,
      'progresso',
      new.equipped_title_key,
      jsonb_build_object('achievement_key', new.equipped_title_key)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists taihenbet_notify_title_change on public.profiles;
create trigger taihenbet_notify_title_change
after update of equipped_title_key on public.profiles
for each row execute function public._notify_title_change();

-- ---------- Moderacao ----------
create or replace function public._notify_moderation_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_title text;
  v_message text;
  v_page text;
begin
  if new.target_user_id is null then return new; end if;

  case new.action
    when 'user_suspended' then
      v_title := 'Conta suspensa pela banca';
      v_message := 'Sua conta foi suspensa. Motivo: ' || coalesce(new.details->>'reason', 'não informado') || '.';
      v_page := 'inicio';
    when 'user_reactivated' then
      v_title := 'Conta reativada';
      v_message := 'A banca devolveu o acesso às operações da sua conta.';
      v_page := 'inicio';
    when 'museum_post_removed' then
      v_title := 'Peça removida do Museu';
      v_message := 'Uma publicação sua foi removida pela Central de Moderação.';
      v_page := 'museu';
    when 'tai_message_removed' then
      v_title := 'Mensagem removida';
      v_message := 'Uma mensagem sua em Para a Tai foi removida pela Central de Moderação.';
      v_page := 'para-tai';
    else
      return new;
  end case;

  perform public._notify_user(
    new.target_user_id, 'moderation', v_title, v_message,
    v_page, new.target_id,
    jsonb_build_object('action', new.action, 'moderator', new.actor_name)
  );
  return new;
end;
$$;

drop trigger if exists taihenbet_notify_moderation on public.admin_moderation_log;
create trigger taihenbet_notify_moderation
after insert on public.admin_moderation_log
for each row execute function public._notify_moderation_log();

-- ---------- Bilhetes esportivos ----------
create or replace function public._notify_sports_bet_settlement()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status = 'pending' and new.status in ('won','lost') then
    perform public._notify_user(
      new.user_id,
      'sports_result',
      case when new.status = 'won' then 'Bilhete esportivo venceu' else 'Bilhete esportivo perdeu' end,
      case when new.status = 'won'
        then 'A banca liquidou seu bilhete vencedor. Pagamento: ' || trim(to_char(coalesce(new.payout, 0), 'FM999999990D00')) || ' TaiCoins.'
        else 'A banca liquidou seu bilhete como perdido. Stake: ' || trim(to_char(coalesce(new.stake, 0), 'FM999999990D00')) || ' TaiCoins.'
      end,
      'historico',
      new.id::text,
      jsonb_build_object('status', new.status, 'stake', new.stake)
    );
  end if;
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.sports_bets') is not null then
    execute 'drop trigger if exists taihenbet_notify_sports_settlement on public.sports_bets';
    execute 'create trigger taihenbet_notify_sports_settlement after update of status on public.sports_bets for each row execute function public._notify_sports_bet_settlement()';
  end if;
end $$;

commit;
